### ISSUE TITLE
Sources Fail to Compile becouse of Missing LDS Files.

### ISSUE THREAD

**Issue by LinuXperia** [cubieboard/Cubietruck_Plus-u-boot#1]
Hi i buyed several days ago a CubieTruck Plus and now i am trying to recompile the sources.
Becouse of missing files the Cubietruck_Plus-u-boot sources could not be compiled.
The missing Files are:
u-boot-2011.09/sunxi_spl/boot0/main/boot0.lds 
u-boot-2011.09/sunxi_spl/fes_init/fes_init.lds
u-boot-2011.09/sunxi_spl/sbrom/main/sboot.lds 

I had to add this three lds files that i found for a H3 board and uploaded them here
https://github.com/LinuXperia/Cubietruck_Plus-u-boot/commit/b510b30292888deadd3f8b06ea4a98d93360630a

With this three missing files i was able finally to successfull compile the sources but the compiled binary differs.
Can you tell me if the missing files are correct or what H8 modification need to be applied to this files as i only found the H3 Files.
Also is it possible to upload this missing files to this repo to so other persons can compile the sources without problem as without them the compilation is broken.
Thank you
LinuXperia

**Comment by allencubie** [comment]
Hi 

i have add the lds files ,please try compiled it .

**Comment by LinuXperia** [comment]
Hi Allen. 
Thank you very much for the support.
Yes i was now able to compile and build the sources for my buyed cubie truck plus 5 board and run and boot the board successful with the new build.
Thanks a lot for fixing the Problem.
The Issue can be colsed.
BTW. Some Developers were hired to port the u-boot loader for the cubietruckplus board to the newest u-boot mainline version. In case some Question arises related to cubietruck plus hardware how can they reach any of you by email so cubietruck plus u-boot and kernel is finally supported in the mainline repo sources as several software like chromium browser does not work with outdated kernel cubietruck ships provide for cubietruck plus?

**Comment by allencubie** [comment]
They can send question to support@cubietech.com．I promise that we will do our best to solve it .
BTW, how can get the  information about the work you said port the u-boot loader to  newest u-boot mainline version.Because I don't know about it before .

**Comment by LinuXperia** [comment]
Hi Allen! 
Thanks for your reply and your help to make u-boot mainline and kernel mainline work on cubietruck plus.

To get mainline u-boot loader compiled for cubietruck you need to clone the original u-boot repo like this
`sudo apt-get install gcc-arm-linux-gnueabi
export ARCH=arm
export CROSS_COMPILE=arm-linux-gnueabi-
git clone git://git.denx.de/u-boot.git
cd u-boot
make Cubietruck_plus_defconfig
make
`
This will produce cross compiled u-boot binaries for the CubieTruck Plus that based on other People works on Cubietruck Plus but only with a limited hardware support.

After this do the following to flash the new binaries to the working cubietruck plus linaro desktop image.
`cp u-boot.bin /root/boot-file/u-boot-spl-sun8iw6p1.bin
cp u-boot-spl.bin /root/boot-file/u-boot-sun8iw6p1.bin

inside cubietruck plus do this
cd /root/boot-file
sudo ./update_sys_config.sh tfcard
`

I tryed to burn the compiled u-boot.bin and u-boot-spl.bin binarys using your update-sysconfig.sh script but it fails! i guess your https://github.com/cubieboard/Cubietruck_Plus-u-boot/blob/master/add_hash.sh https://github.com/cubieboard/Cubietruck_Plus-products/blob/master/cb5/cb5-linaro-desktop-hdmi/overlay/root/boot-file/update_sys_config.sh and  need to be adapted to work with u-boot mainline version! As a example this step here from your Makefile sources

https://github.com/cubieboard/Cubietruck_Plus-u-boot/blob/a2f7a0903f4c393163fc656ae2af557bcaaff3f6/u-boot-2011.09/Makefile

`@git show HEAD --pretty=format:"%H" | head -n 1 > cur.log
@../add_hash.sh -f sunxi_spl/fes_init/fes1.bin -m boot0

@git show HEAD --pretty=format:"%H" | head -n 1 > cur.log
513			@../add_hash.sh -f sunxi_spl/boot0/boot0_nand.bin -m boot0`

more patches to get compile u-boot and linux kernel main line for cubietruck plus can be found here =>
https://github.com/LinuXperia/lib/commit/43dc42fec9bb10c2664fa4735a6faba5671ff8de

Example:
https://github.com/LinuXperia/lib/commit/43dc42fec9bb10c2664fa4735a6faba5671ff8de#diff-018fb3b9e83b16ea149d7cdf7b6fb640

> +diff --git a/arch/arm/dts/sun8i-a83t-cubietruck-plus.dts b/arch/arm/dts/sun8i-a83t-cubietruck-plus.dts
>  +index 8437c8f59e..a56542b2bd 100644
>  +--- a/arch/arm/dts/sun8i-a83t-cubietruck-plus.dts
>  ++++ b/arch/arm/dts/sun8i-a83t-cubietruck-plus.dts
>  +@@ -46,7 +46,7 @@
>  + #include "sun8i-a83t.dtsi"
>  + 
>  + / {
>  +-	model = "Cubietech Cubietruck Plus";
>  ++	model = "Allwinner A83T Cubietech Cubietruck Plus";
>  + 	compatible = "cubietech,cubietruck-plus", "allwinner,sun8i-a83t";
>  + 
>  + 	aliases {
>  +@@ -58,6 +58,56 @@
>  + 	};
>  + };
>  + 
>  ++&nfc {
>  ++	pinctrl-names = "default";
>  ++	pinctrl-0 = <&nand_pins_a>, <&nand_cs0_pins_a>, <&nand_rb0_pins_a>;
>  ++	status = "okay";
>  ++
>  ++	nand@0 {
>  ++		reg = <0>;
>  ++		allwinner,rb = <0>;
>  ++		nand-ecc-mode = "hw";
>  ++		nand-on-flash-bbt;
>  ++
>  ++		partitions {
>  ++			compatible = "fixed-partitions";
>  ++			#address-cells = <2>;
>  ++			#size-cells = <2>;
>  ++
>  ++			partition@0 {
>  ++				label = "SPL";
>  ++				reg = <0x0 0x0 0x0 0x200000>;
>  ++			};
>  ++
>  ++			partition@200000 {
>  ++				label = "SPL.backup";
>  ++				reg = <0x0 0x200000 0x0 0x200000>;
>  ++			};
>  ++
>  ++			partition@400000 {
>  ++				label = "U-Boot";
>  ++				reg = <0x0 0x400000 0x0 0x200000>;
>  ++			};
>  ++
>  ++			partition@600000 {
>  ++				label = "U-Boot.backup";
>  ++				reg = <0x0 0x600000 0x0 0x200000>;
>  ++			};
>  ++
>  ++			partition@800000 {
>  ++				label = "env";
>  ++				reg = <0x0 0x800000 0x0 0x200000>;
>  ++				read-only;
>  ++			};
>  ++
>  ++			partition@a00000 {
>  ++				label = "rootfs";
>  ++				reg = <0x0 0xa00000 0x01 0xff000000>;
>  ++			};
>  ++		};
>  ++	};
>  ++};
>  ++
>  + &ehci0 {
>  + 	status = "okay";
>  + };
>  +@@ -72,6 +122,67 @@
>  + 	status = "okay";
>  + };
>  + 
>  ++&emac {
>  ++	pinctrl-names = "default";
>  ++	pinctrl-0 = <&emac_rgmii_pins>;
>  ++	phy = <&phy1>;
>  ++	phy-mode = "rgmii";
>  ++	status = "okay";
>  ++	allwinner,rx-delay = <7>;
>  ++	allwinner,tx-delay = <7>;
>  ++	/* TODO: add regluator supplies for phy */
>  ++
>  ++	phy1: ethernet-phy@1 {
>  ++		  reg = <1>;
>  ++	};
>  ++};
>  ++
>  ++&mmc0 {
>  ++	pinctrl-names = "default";
>  ++	pinctrl-0 = <&mmc0_pins_a>, <&mmc0_cd_pin_reference_design>;
>  ++	vmmc-supply = <&reg_vcc3v0>;
>  ++	cd-gpios = <&pio 5 6 GPIO_ACTIVE_HIGH>; /* PF6 */
>  ++	bus-width = <4>;
>  ++	cd-inverted;
>  ++	status = "okay";
>  ++};
>  ++
>  ++&mmc2 {
>  ++	pinctrl-names = "default";
>  ++	pinctrl-0 = <&mmc2_8bit_pins>;
>  ++	vmmc-supply = <&reg_vcc3v0>;
>  ++	bus-width = <8>;
>  ++	non-removable;
>  ++	cap-mmc-hw-reset;
>  ++	status = "okay";
>  ++};
>  ++
>  ++&r_rsb {
>  ++	status = "okay";
>  ++};
>  ++
>  ++&reg_usb1_vbus {
>  ++	gpio = <&pio 3 24 GPIO_ACTIVE_HIGH>; /* PD24 */
>  ++	status = "okay";
>  ++};
>  ++
>  ++&uart0 {
>  ++	pinctrl-names = "default";
>  ++	pinctrl-0 = <&uart0_pins_b>;
>  ++	status = "okay";
>  ++};
>  ++
>  ++&usbphy {
>  ++	usb1_vbus-supply = <&reg_usb1_vbus>;
>  ++	status = "okay";
>  ++};
>  ++
>  + &usb_otg {
>  ++	/* VBUS detection/drive support in PMIC required for OTG */
>  ++	dr_mode = "host";
>  + 	status = "okay";
>  + };
>  ++
>  ++&usb1_vbus_pin_a {
>  ++	allwinner,pins = "PD24";
>  ++};
